### ISSUE TITLE
pip install qrbill defect

### ISSUE THREAD

**Issue by gabejackson** [claudep/swiss-qr-bill#32]
Just to let you know that the setup is broken:
`pip install qrbill
Collecting qrbill
  Downloading https://files.pythonhosted.org/packages/d6/54/8997ebb7425cdbab592d93600f4e2b3f7bad6a64a932658abf8495e065ba/qrbill-0.5.tar.gz
  Running setup.py (path:/tmp/pip-build-UtL0xF/qrbill/setup.py) egg_info for package qrbill produced metadata for project name unknown. Fix your #egg=qrbill fragments.
Installing collected packages: unknown
  Running setup.py install for unknown ... done
Successfully installed unknown-0.0.0`

**Comment by claudep** [comment]
From what I read around the Web about this problem, it looks like this is due to a too-old setuptools version. Most articles about that mention the workaround `pip install setuptools --upgrade` before installing.
For example: https://github.com/lief-project/LIEF/issues/108

**Comment by gabejackson** [comment]
thx claudep, that was exactly it (sorry, it was a really old project on python 2.7. i only did a pip upgrade, but forgot about setuptools). thx again!

**Comment by aloistr** [comment]
I found this thread just now. It worked also for me on RHEL 7, first upgrade pip, the upgrade setuptools, then install qrbill
