### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by aloistr** [claudep/swiss-qr-bill#36]
I am trying qrbill on RHEL 7, in a terminal with usual utf8 encoding
 LANG=en_US.UTF-8

qrbill -h
Traceback (most recent call last):
  File "/usr/bin/qrbill", line 7, in <module>
    from qrbill import QRBill
  File "/usr/lib/python2.7/site-packages/qrbill/__init__.py", line 1, in <module>
    from .bill import QRBill  # NOQA
  File "/usr/lib/python2.7/site-packages/qrbill/bill.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/qrbill/bill.py on line 25, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Line 25 is:
        'fr': 'Compte / Payable à',
where à is an utf8 double byte character sequence.

**Comment by claudep** [comment]
You should be using Python 3!

**Comment by aloistr** [comment]
On RHEL 7 (or centos 7) python2.7 is the standard python.
Many system scripts depend on it.

I have installed python3.7 at an alternative location, /usr/local/bin/python3.7
but do not know how I get pip and qrbill installed so that they use this Python version.

**Comment by claudep** [comment]
I strongly suggest to use Python virtualenv. You can then install and upgrade packages inside the virtual Python environment as you wish without touching system global packages. I guess you'll find enough documentation around the Web.

**Comment by aloistr** [comment]
I reinstalled qrbill with pip3.7  and this seems to work. 
Thank you
