### ISSUE TITLE
Adding a reference number

### ISSUE THREAD

**Issue by aloistr** [claudep/swiss-qr-bill#37]
I try to add a reference number.
qrbill --account "CH58 0079 1123 0008 8901 2" --creditor-name "Robert Schneider AG" --creditor-street "Rue du Lac 1268" --creditor-postalcode "2501" --creditor-city "Biel" --extra-infos "Bill No. 3139 for garden work and disposal of cuttings." --debtor-name "Pia Rutschmann" --debtor-street "Marktgasse 28" --debtor-postalcode "9400" --debtor-city "Rorschach" --due-date "2019-10-31" --language "de" --reference-number "00 00000 00000 88403 48716 00166" --amount "79.90"
Error: A QRR reference number is only allowed for a QR-IBAN
I do not understand this error message.

**Comment by claudep** [comment]
Sorry, the IBAN numbers in the README are not correct. Some IBAN numbers require the presence of a reference number, while others forbid the reference number. I'll fix the README ASAP.

**Comment by aloistr** [comment]
I got it, Postfinance must give us a special QR-Iban which must be in postion 4-9 between 30000 and 32000

**Comment by claudep** [comment]
Exactly.
