### ISSUE TITLE
qr-code rectangle alone

### ISSUE THREAD

**Issue by aloistr** [claudep/swiss-qr-bill#38]
We would like to use your code to generate the QR-code rectangle alone, without the complete "Einzahlungsschein".
The reason is that we generate our invoices as PDF files with the cairo library.
We can convert the QR-code square from svg into png, and then import it in cairo and place it where it should appear.
The rest of the form we can print directly ourselves.

That way, the user can still copy-paste textual elements from the PDF, like IBAN or reference number into his online banking app, if his online banking does not handle QR-code or has no camera to scan it.

If we would transform the whole svg inclding its text parts into a png image, the copy/paste ability for text strings would be lost.

**Comment by claudep** [comment]
`cairosvg` is able to convert SVG into PDF. Did you try that solution?

**Comment by aloistr** [comment]
We are not so far yet. I have only this afternoon started to look around for a qr-code generating library and found yours.
I now saw already the the qrcode module you use can produce png, and I think if I modify your call somewhat,
qrcode.make will create exactly the png I need.
I will have to check under which license you have published your code.

def qr_image(self):
        factory = qrcode.image.svg.SvgPathImage
        return qrcode.make(
            self.qr_data(),
            image_factory=factory,
            error_correction=qrcode.constants.ERROR_CORRECT_M,
        )

**Comment by aloistr** [comment]
PS: we program in C, and us the C version of cairo library. cairosvg is a Python library, seems not to have a C version.

**Comment by claudep** [comment]
I think this is a very specific use case, and it could be solved by using the `QRBill.qr_image()` method.
