### ISSUE TITLE
Position of top_line

### ISSUE THREAD

**Issue by iom10** [claudep/swiss-qr-bill#42]
Thank you very much for sharing your project with us. I am really satisfied with the results. Although I have a noticed that the top_line is not properly aligned. 

The top_line is located at y-coordinate 0 mm and has a width of 0.282 mm. After converting the output to a PDF file, the top half of the top_line is cut off, since the center of the line is at y = 0. It is a quick fix, I propose to change the coordinates of the top_line to be at y = 0.141 mm.

Have a nice day.

**Comment by claudep** [comment]
Thanks for your reports!
