### ISSUE TITLE
Output to pdf instead of svg

### ISSUE THREAD

**Issue by SIELA1915** [claudep/swiss-qr-bill#44]
Thx for this great library! 
Export to pdf would be appreciated. Do you plan to add this option?

**Comment by claudep** [comment]
Not directly, I'd rather suggest svglib usage. Is the example in that PR helps? #45

**Comment by SIELA1915** [comment]
Thanks. Works - just the scissors are missing (a rectangle is printed instead).

**Comment by claudep** [comment]
Thanks for confirmation, I created #46 for the scissors issue.
