### ISSUE TITLE
newline

### ISSUE THREAD

**Issue by AntonMezger** [claudep/swiss-qr-bill#48]
Hi,

super project, we will integrate in our access database in order to generate qrr bills.

One problem arises from the fact that our receipt name is very long (an association) and we would like to know how we could split the name in two lines. I attach our example

![bill](https://user-images.githubusercontent.com/12997672/105577455-0965ec80-5d7a-11eb-925d-aea6d5f73c05.png)

best regards and stay healthy

**Comment by AntonMezger** [comment]
perhaps a possibility to solve this problem, is to add a line3 so that we could have the following

i.e. instead of 👍 
creditor={'name': 'SGED Schweiz. Ges. für Endokrinologie u.', 'line1': 'Diabetologie', 'line2': 'Rütistrasse 3A, CH-5400 Baden', 'country': 'CH',}

creditor={'name': 'SGED Schweiz. Ges. für Endokrinologie u.', 'line1': 'Diabetologie', 'line2': 'Rütistrasse 3A', 'line3'= CH-5400 Baden', 'country': 'CH',}

and then why not: line4, line5?

thank you for bothering

best regards

Anton

**Comment by claudep** [comment]
Are you able to test the current master branch? Otherwise, I plan to release a new version rather soon.

**Comment by AntonMezger** [comment]
I tested it and it works fine. You did a great job, thank you

However addresses can be quite complicated and long. (ex. 'street': 'Solinas Department of Molecular and Clinical Medicine Wallenberglab Su Sahlgrenska')

would it be possible that one could split this with a newline, so that we also get multiple line?

best regards

**Comment by claudep** [comment]
It should also work with long addresses, did you try it?

**Comment by AntonMezger** [comment]
yes, but we hid a limit of 70 characters. by the way, it should be possible to obtain an address for foreign countries. i.e when we send a bill to sweden, the country code would be SE, but now the code limits to Switzerland and Liechtenstein.
