### ISSUE TITLE
newline still

### ISSUE THREAD

**Issue by AntonMezger** [claudep/swiss-qr-bill#50]
address not broken down.  we hit a limit of 70 characters and an address should be cut at specific points. By the way, it should be possible to obtain an address for foreign countries. i.e when we send a bill to sweden, the country code would be SE, but now the code limits to Switzerland and Liechtenstein.

debtor={'name': 'Monsieur Ph.D. xyz', 'street': 'Solinas Department of Molecular and Clinical Medicine Wallenberglab Su Sahlgrenska', 'house_num': '61', 'pcode': 'S-41345', 'city': 'Göteborg/Sweden', 'country': 'CH',}

_Originally posted by @AntonMezger in https://github.com/claudep/swiss-qr-bill/issues/48#issuecomment-766086735_

**Comment by AntonMezger** [comment]
when specifying longer lines then 70, the previous modification by going on the next line works fine. However a \n in the text would be nice to have for a next line.

**Comment by claudep** [comment]
Please try to keep one subject by ticket, tickets are free :-)

The limit of 70 characters comes from the specs. See https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf, section 4.3.3

**Comment by claudep** [comment]
For the example Swedish address, you should enter it as` 'pcode': '41345', 'city': 'Göteborg', 'country': 'SE',`

**Comment by AntonMezger** [comment]
Everything works fine, super application

thanks a lot

best regards

Anton
