### ISSUE TITLE
QR bill not accepted by postfinance

### ISSUE THREAD

**Issue by samuel-iseli** [claudep/swiss-qr-bill#52]
The generated qrbill is not accepted by postfinance because it doesn't fit inside the expected region.
This only happens, when more data is added (eg. debtor address) as the qr code then grows in size.

I added the output of the postfinance testplatform for illustration of the problem.

Will see that I can correct this an submit a pull request.

[example_qrr_Visuelle_Kontrolle(1).pdf](https://github.com/claudep/swiss-qr-bill/files/5950715/example_qrr_Visuelle_Kontrolle.1.pdf)

**Comment by claudep** [comment]
Thanks for the report, would be great if you could submit a PR!

**Comment by samuel-iseli** [comment]
Implemented the changes, see PR #53.

Attached the visual control doc from testplatform after the adjustment. 
The 73 in the filename means qrcode with a width of 73.

[example_qrr_73_new.pdf](https://github.com/claudep/swiss-qr-bill/files/5954575/example_qrr_73_new.pdf)
