### ISSUE TITLE
changes due to styleguide

### ISSUE THREAD

**Issue by AntonMezger** [claudep/swiss-qr-bill#56]
The latest version does not follow the guidelines as corrected by UBS. The main things to correct are the following:

QR-Code must be 46x46mm
Swiss cross must be 7x7mm
the right part must be 5 mm right from the QR-Code
the bottom part is also too low

I corrected all this in the attached version, please have a look and perhaps integrate by improving the code

[bill.zip](https://github.com/claudep/swiss-qr-bill/files/6318887/bill.zip)

**Comment by claudep** [comment]
Thanks a lot for the proposed changes! However, the code changed a bit since you amended `bill.py`. It would be great to check if the latest code (0.6.0) still suffers from the same issues, and in that case, suggest a pull request.

**Comment by AntonMezger** [comment]
0.6.0 has been tried, but the only thing that seems correct is that the qr-code is sitting 5mm from the cut border. Size is not 46mm, cross is not 7mm and the right part is not sitting 5mm from the qr-code.

**Comment by claudep** [comment]
I splitted each reported problem to its own issue.

**Comment by claudep** [comment]
Now the master branch should be in better shape. Would appreciate testing before a release (or other fixes).
