### ISSUE TITLE
Scissors missing on top seperation line

### ISSUE THREAD

**Issue by anjagenser** [claudep/swiss-qr-bill#65]
Currently the scissor is only shown on the vertical seperation line. However; in the standard it says that a scissor symbol should appear on both of those lines. 

I tried adding it to the top line, but my attempt doesn't look great:

```python
grp.add(dwg.text(
                "✂", insert=(add_mm(60, mm(-1.5)), 10),
                font_size=16, font_family='Helvetica'
            ))
```

Possibly you could come up with a better way and help me out?

**Comment by claudep** [comment]
The problem with adding scissors on horizontal line is that we have to increase the height of the bill to make the symbol entirely visible. Do you think that having only half of scissors visible would be enough?

**Comment by claudep** [comment]
Note that the spec also allows replacing the scissors by the text `A détacher avant le versement` above the bill.

**Comment by anjagenser** [comment]
I see, you are totally right. I think I would prefer increasing the height of the bill a tiny bit.

**Comment by claudep** [comment]
There is now a pull request, maybe you want to test it?
