### ISSUE TITLE
small one

### ISSUE THREAD

**Issue by joff13** [claudep/swiss-qr-bill#67]
Hi 
In README.rst
line
`>>> renderPDF.drawToFile(drawing, "file.pdf")`

shoud be indented

nice job and thanks for sharing

**Comment by claudep** [comment]
Thanks for reporting, but are you sure the indentation is needed? I think the temp file can be closed during the final rendering. Did you get an error yourself?

**Comment by joff13** [comment]
yes I’m sure 

attached the output

**Comment by claudep** [comment]
Sorry, I'm not seeing any output. I just tried and it succeeded without the indent. Could you attach the traceback?

**Comment by joff13** [comment]
Maybe it's my problem…
I copy in the email hopping it works

$ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> from qrbill.bill import QRBill
>>> from svglib.svglib import svg2rlg
>>> from reportlab.graphics import renderPDF
>>> my_bill = QRBill(
...     account='CH5800791123000889012',
...     creditor={
...             'name': 'Jane', 'pcode': '1000', 'city': 'Lausanne', 'country': 'CH',
...     },
...     amount='22.45',
... )
>>> with tempfile.TemporaryFile(encoding='utf-8', mode='r+') as temp:
...     my_bill.as_svg(temp)
...     temp.seek(0)
...     drawing = svg2rlg(temp)
... renderPDF.drawToFile(drawing, "file.pdf")
  File "<stdin>", line 5
    renderPDF.drawToFile(drawing, "file.pdf")
    ^
SyntaxError: invalid syntax
>>> 
>>> 
>>> with tempfile.TemporaryFile(encoding='utf-8', mode='r+') as temp:
...     my_bill.as_svg(temp)
...     temp.seek(0)
...     drawing = svg2rlg(temp)
...     renderPDF.drawToFile(drawing, "file.pdf")
... 
0

**Comment by claudep** [comment]
Thanks. It's a bit weird, but not related to the fact it is inside or outside the `with` (it wouldn't be a SyntaxError). Maybe a lonely initial space?
I'm closing the issue (not the discussion :smile: )

**Comment by joff13** [comment]
don't’ know… anyway peanuts ….. 
bye claudio
