### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by yene** [claudep/swiss-qr-bill#72]
hi, claudep
thanks for creating the project, sadly I can not use it as long it is under GPL.
Is it possible to change the license to an MIT license?

**Comment by kaywolter** [comment]
Hello Claudep,

is there a possibility for an alternative license? We would also love to use your project but if GPL is the only option we need to switch to another solution.

Cheers, Kay

**Comment by claudep** [comment]
I contacted contributors (those for which I have an email) for feedback.

**Comment by kurtkeller** [comment]
As one of the contributors, I have no problem with changing the license to a more permissive one.

**Comment by kaywolter** [comment]
Hi Claudep,

any ETA when you make a decision on the license yet?

Thanks a lot for your efforts! Would love to integrate your module.

Cheers, Kay

**Comment by claudep** [comment]
I would say not before December 13th to give contributors some time to chime in.

**Comment by kaywolter** [comment]
Hi Claudep,

any updates on the license issue?

Thanks, Kay
