### ISSUE TITLE
Incorrect vertical position of blank amount rect on receipt

### ISSUE THREAD

**Issue by marco-websource** [claudep/swiss-qr-bill#74]
Hi

I believe the vertical position of the blank rect for the amount is not correct on the receipt. It interferes with the text "acceptance point" and it does not match the examples by SIX.

I fixed this problem by moving the rect up by 4.5mm:
```
--- qrbill/bill.py.orig	2022-03-02 23:43:53.816789588 +0100
+++ qrbill/bill.py	2022-03-03 00:25:06.589648708 +0100
@@ -559,7 +559,7 @@
             grp.add(dwg.text(format_amount(self.amount), (add_mm(margin, mm(12)), mm(77)), **self.font_info))
         else:
             self.draw_blank_rect(
-                dwg, grp, x=add_mm(margin, mm(25)), y=mm(75),
+                dwg, grp, x=add_mm(margin, mm(25)), y=mm(70.5),
                 width=mm(27), height=mm(11)
             )
 
```
I suggest to consider changing this.

Thanks for providing this package! It has proven useful to me.
Marco

**Comment by claudep** [comment]
In fact, I think the whole currency blocks are a bit two low, on both parts. Would you feel like fixing those positions?
