### ISSUE TITLE
postfinance doesnt accept generated qr-code

### ISSUE THREAD

**Issue by marcel-holstein** [claudep/swiss-qr-bill#75]
Hi, our postfinance doesnt accept our generated qr-code because there are characters in line 30 that are not allowed (extra_infos, '##' character for visual line split). Is it possible to remove the character after line split (line 680 in bill.py)? Currently its readded after line split.

**Comment by claudep** [comment]
I don't remember if in a previous spec, the `//` separation sequence was `##`. What about replacing `##` by `//` in the code now? Would that suit your use case?

**Comment by claudep** [comment]
See the above pull request for my suggested fix.

**Comment by claudep** [comment]
@marcel-holstein Any feedback on my proposal?

**Comment by marcel-holstein** [comment]
Yeah, looks promising. Thank you.

**Comment by claudep** [comment]
Thanks for checking and for the report, of course!
