### ISSUE TITLE
due_date

### ISSUE THREAD

**Issue by Jeandy22** [claudep/swiss-qr-bill#84]
There is a field called "due_date" and it appears on the qr-bill as (in french) "Payable jusqu'au". Is this really allowed, as I don't see this field appear on SIX payment standards documentation ?

**Comment by claudep** [comment]
I think you are right. I'm sure it used to be in previous versions of the standard, but the latest version doesn't mention it any longer. I guess we should remove that part.

**Comment by claudep** [comment]
Do you intend to provide a patch for that?

**Comment by claudep** [comment]
I just happened to see an example from a big insurance company, which is using the Extra information section to add a line like "Echéance: 01.10.2022".

So we might keep the due-date command line argument, and move that information under Extra information.

**Comment by yene** [comment]
just make sure you don't do breaking changes, we use qbill in production

**Comment by Jeandy22** [comment]
Thanks for the information. I planed to add a warning or so if due_date is used. What do you think about this ?

**Comment by claudep** [comment]
> just make sure you don't do breaking changes, we use qbill in production

Then pin the qrbill version in your dependency file. When you upgrade, read the Changelog and decide/test if you can upgrade without regressions.

**Comment by claudep** [comment]
> Thanks for the information. I planed to add a warning or so if due_date is used. What do you think about this ?

I don't think the current way of printing the due date on bills is conforming to the standard, so I'd rather move the way it's printed under "Extra informations".

**Comment by Jeandy22** [comment]
> > Thanks for the information. I planed to add a warning or so if due_date is used. What do you think about this ?
> 
> I don't think the current way of printing the due date on bills is conforming to the standard, so I'd rather move the way it's printed under "Extra informations".

OK, I can do that.

**Comment by dschmide** [comment]
[claudep](https://github.com/claudep)

Could you link the specification that you're referring to? It's not clear if you're referring to the same SIX payment standards documentation - english / french or what date the version was released. This would help a lot.

**Comment by claudep** [comment]
The latest version of the `Swiss Implementation Guidelines for the QR-bill` is `Version 2.2, with effect from 22 February 2021`, available from https://www.six-group.com/en/products-services/banking-services/standardization.html.
