### ISSUE TITLE
line break in additional_information isnt shown and breaks many scanners

### ISSUE THREAD

**Issue by dschmide** [claudep/swiss-qr-bill#86]
Providing a line break character "\n" in the string for the additional_information parameter will cause problems with many scanners. 

steps to reproduce:

QRBill(additional_information= f"Hello \n Line break")

The line break will not be visible in the human-readable text field, and will cause an error in the encoded bytes data of the qr code, which many scanners will be unable to decode

Even though some scanners can properly decode the resulting bytes, I do suggest sanitizing line breaks from the provided string, because the line break itself isnt properly displayed anyway, and this might cause many issues for users trying to use multiple lines in this section.

**Comment by dschmide** [comment]
No, I just removed my line breaks in the inputs. The fix for me is simple enough, but it's quite hard to even realize what the problem is, because proprietary scanners that I don't have access to might be having a problem. (ZKB, Postfinance, etc...)

I think a simple fix could be implemented on line 407 in bill.py by adding self.additional_info.replace("\n", " ") or something. There might also be a missing \r ? You better look into this yourself and get to the bottom of why the line breaks a) aren't displayed and b) produce an error in the bytecode of the QR code.

![Hello  n Line break  n  n](https://user-images.githubusercontent.com/427755/191248854-e674a7c1-667e-4c5b-be4a-1b217db4fb82.png)

![line break decoded](https://user-images.githubusercontent.com/427755/191249157-e7b67d7a-0422-4ef0-9a53-59e210e185ed.png)
(see missing line break, no carriage return, -> added whitespace on second line, QR code can't be decoded by many apps)

**Comment by claudep** [comment]
Could you please have a look at the proposed fix (#87)?

**Comment by dschmide** [comment]
I think that solves the issue with the bytes data in the qr code but I dont see why it should change anything about the visual linebreaks not showing. I'm fine with this, but I guess the commit name isnt technically correct - they still won't show.

I'll checkout this version and test it tomorrow. Thank you for looking into this!

**Comment by claudep** [comment]
The visual fix should be done through `for text in line.splitlines():` in `wrap_infos`. We'll see…

**Comment by dschmide** [comment]
You are right, this also solves the line breaks visually not showing up. They all do now, and line breaks are replaced by whitespace in the bytecode. I would use this, its a clear improvement. Thank you very much

![fixed line breaks](https://user-images.githubusercontent.com/427755/191456879-cc3875ba-1f8a-4fc8-b620-6f5171d95933.png)

![replaced line breaks](https://user-images.githubusercontent.com/427755/191456920-5e24f4f6-7b5f-4beb-8d0b-96cf6eef6718.png)

**Comment by claudep** [comment]
I guess we'll stick with the current behavior for now. I struggle to find a real use case for adding blank lines inside content.
