### ISSUE TITLE
invalid QR Code generation

### ISSUE THREAD

**Issue by qxsch** [claudep/swiss-qr-bill#92]
The SVG seems to generate an *invalid QR Code* and the qrcode image cannot be validated, f.e. here:  https://www.swiss-qr-invoice.org/validator/
In addition, the QR Code also *cannot* be scanned with a mobile app.

The text data that gets generated within ``def qr_data(self):`` method is *valid*. But there seems to be an issue with ``qrcode.make`` that generates an *invalid QR code*.

Also the following returns the same *invalid* QR code. So it is not an issue with SVG.
There seems to be an issue with the qrcode library or probably text encoding(??).
```python
codeimg = qrcode.make(
    bill.qr_data(),
    error_correction=qrcode.constants.ERROR_CORRECT_M,
    border=0,
)
codeimg.save("qrcode.png")
```

**Comment by qxsch** [comment]
``len(bill.qr_code())`` is 211 characters (no special ones, just latin)

The following qrcode is **scannable** f.e. with iphone camera:
```python
codetxt = "hello"
codeimg = qrcode.make(codetxt)
codeimg.save("qrcode.png")
```

The following qrcode is **scannable** f.e. with iphone camera:
```python
codeimg = qrcode.make(
    bill.qr_data()[:100],
    error_correction=qrcode.constants.ERROR_CORRECT_M,
    border=0,
)
codeimg.save("qrcode.png")
```

The following qrcode looks normal, but is **NOT scannable** f.e. with apple camera (and also not with a banking app):
```python
codeimg = qrcode.make(
    bill.qr_data(),
    error_correction=qrcode.constants.ERROR_CORRECT_M,
    border=0,
)
codeimg.save("qrcode.png")
```

**Comment by qxsch** [comment]
# solution 
replace qrcode with segno works!
```
import segno
codeimg = segno.make(bill.qr_data())
codeimg.save("qrcode.png")
```

**Comment by claudep** [comment]
You may have been hit by https://github.com/lincolnloop/python-qrcode/issues/304

**Comment by iulica** [comment]
Yep, I also came here first, I thought raising an issue, but since the problem is not here, I decided against it.
