### ISSUE TITLE
Please add EPC-QR-Code

### ISSUE THREAD

**Issue by Mannshoch** [claudep/swiss-qr-bill#95]
It would be nice If it is possible to create an [European Payments Council QR-Code](https://de.wikipedia.org/wiki/EPC-QR-Code)

**Comment by Mannshoch** [comment]
Spec: https://de.wikipedia.org/wiki/EPC-QR-Code#EPC-QR-Code_Dateninhalt
Relation: https://de.wikipedia.org/wiki/EPC-QR-Code#Situation_in_der_Schweiz

I'don't have more

**Comment by claudep** [comment]
Thanks for the links. As what I understand, this would be a different functionality. My current position is for this package to focus on the Swiss version of QR bills (based on "do one thing and do it well"). There are other packages that handle EPC QRs, e.g. https://pypi.org/project/py-epc-qr/
