### ISSUE TITLE
Add possibility to use it in Browser

### ISSUE THREAD

**Issue by Mannshoch** [claudep/swiss-qr-bill#96]
I came across an article that there are possibilities to use Python in Browser called WASM.
It would be nice if you could create such a way. It would allow my club to auto generate a QR-Code and include a custom Remittance text.

**Comment by claudep** [comment]
If you want to use any Python package in the browser, I don't think that's a task for the package itself. If you have concrete ideas or patches, feel free to reopen and suggests them.
